### ISSUE TITLE
Switch everything to JSON instead of XML

### ISSUE THREAD

**Issue by ekoval** [yola/teamsupport-python#22]
For some reason we're now using XML api, which brings needless complexity and problems. Let's switch everything to JSON.

**Comment by stefanor** [comment]
I would assume that the JSON API didn't exist at the time.

**Comment by ekoval** [comment]
It does and it works. I've checked GET requests - they work. Create Ticket still doesn't work for me, but I can't see any info on TS portal regarding this.

**Comment by ekoval** [comment]
Oh, sorry, you meant it didn't exist by the time we were writing this code. My Ukrish :)
